#include "FunctionsOfAscPrioQueue.cpp"

int main(){
    cout<<"Welcome to the world of programming\n";
    cout<<"This program is dedicated to explore Ascending Priority Queue\n";
    int size;
    cout<<"Please enter the maximum size of your Priority Queue = ";
    cin>>size;
    PrioQueue pq(size);

    /* !! Don't Edit the Above code otherwise program will malfunction !! */


    // Sample Code written so that you can understand how to implement these functions
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("AAA",1);
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    pq.push("BBB",1);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("CCC",3);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("DDD",4);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("EEE",1);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("FFF",1);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("GGG",3);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push("HHH",4);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    string a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    return 0;
}