#include "FunctionsOfQueue.cpp"

int main(){
    cout<<"Welcome to the world of programming\n";
    cout<<"This program is dedicated to explore Regular Queue\n";
    int size;
    cout<<"Please enter the maximum size of your Queue = ";
    cin>>size;
    Queue pq(size);

    /* !! Don't Edit the Above code otherwise program will malfunction !! */
    // Sample Code written so that you can understand how to implement these functions
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(1);
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    pq.push(2);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(3);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(4);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(5);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(6);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(7);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.push(8);
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    int a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    a = pq.pop();
    cout<<a<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    pq.print();
    cout<<"Front element :- "<<pq.front()<<endl;
    cout<<"Rear element :- "<<pq.rear()<<endl;
    cout<<"Current Size = "<<pq.count()<<endl;
    cout<<"Is full :- "<<pq.isFull()<<endl;
    cout<<"Is empty :- "<<pq.isEmpty()<<endl;
    return 0;
}